---
title: "Western Biodiversity Inventory - Exploration"
author: "Jackson Kusack"
date: "`r Sys.Date()`"
output: html_document

params:
  download:
    label: "Update Data"
    value: FALSE
    input: select
    choices: [TRUE,FALSE]
---

```{r setup, include=FALSE, comment=""}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```

```{r packages, message=F, warning=F}
library(tidyverse)
library(rinat)
library(jsonlite)

source("R/get_inat_user_stats_v2.R")
source("C:/Users/jacks/Documents/GitHub/iNatTools/R/iNat_sc.R")
```

## Observer Effort Data

```{r eval = FALSE}
# Create dataframes 
observer.df <- data.frame(1:12,rep(0,12))
names(observer.df) <- c('Month','Observers')

# For loop to download data
for (i in 1:12) {
    observer.df[observer.df$Week == i] <- get_inat_user_stats_v2(project = "biodiversity-inventory-at-western", month = i)$total
    Sys.sleep(1) # Make sure the loop takes at least 1s, to stay above the recommended API call limit
}

write.csv(observer.df, file = "Data/Observer/observer.df.csv", row.names = F)
```

## Observation Data

```{r eval = params$download}
observations <- get_inat_obs_project("biodiversity-inventory-at-western", type = c("observations", "info"), raw = FALSE) %>%
  select(!c(photos, tag_list))

write.csv(observations, file = "C:/Users/jacks/Documents/GitHub/Western-Biodiversity-Inventory_rinat/Data/observation.df.csv", row.names = F)
```

```{r eval = T, fig.width = 6.5, fig.height = 15}
observations <- read.csv("Data/observation.df.csv")

observations.summary <- observations %>%
  mutate('Month' = lubridate::month(lubridate::ymd(observed_on))) %>%
  rename('Taxon' = iconic_taxon.name) %>%
  filter(is.na(Taxon) == F) %>%
  filter(quality_grade == "research") %>%
  group_by(Month, Taxon) %>%
  summarize(Observations = n()) 
  
(p.obs <- ggplot() + 
  geom_point(data = observations.summary, aes(x = Month, y = Observations, col = Taxon)) + 
  geom_line(data = observations.summary, aes(x = Month, y = Observations, col = Taxon)) +
  scale_y_continuous(limits=c(0,NA)) + 
  ylab('Observers (count)') + xlab('Month') + facet_wrap(~Taxon, scales = "free_y", ncol = 1) + 
  theme_linedraw() + theme(panel.grid = element_blank(), axis.text.x = element_text(size = 8)))

png(filename = "Figures/Research_grade_observations_xMonth_xTaxon.png",
    res = 300, 
    width = 4, 
    height = 12,
    units = 'in')
p.obs
dev.off()
```

# Most recent species/genus added: top 50

```{r}
unique(observations$taxon.rank)

observations %>% 
  filter(taxon.rank %in% c("species","genus","subspecies","complex","subgenus")) %>%
  group_by(taxon.common_name.name, taxon.name) %>%
  summarize(first.observation = min(observed_on)) %>%
  arrange(desc(first.observation)) %>%
  data.frame() %>%
  head(50)
```

# Most rare species seen on campus: top 50

```{r}
observation.counts <- iNat_sc(project_id = 'biodiversity-inventory-at-western', quality_grade = "research", d1 = "2022-04-01", d2 = "2023-03-31")

observation.counts %>% 
  arrange(taxon.observations_count) %>%
  select(count, taxon.observations_count, taxon.name, taxon.preferred_common_name) %>%
  rename('total.count' = taxon.observations_count) %>%
  rename('common.name' = taxon.preferred_common_name) %>%
  data.frame() %>%
  head(50)
```
